### ISSUE TITLE
Aggregation based

### ISSUE THREAD

**Issue by zJaska** [MuhammadAshiqAmeer/Federated-Learning-Intel-OpenFL#1]
Hey!

I like your project, can I ask if you can also implement aggregation-based FL?

Can I have a chance to contact you in private?

**Comment by zJaska** [comment]
Another question, how can i change the dataset to run experiment with another dataset?

**Comment by MuhammadAshiqAmeer** [comment]
hi,

Actually aggregated based approach is simpler than director based approach. I started learning OpenFL from aggregated based approach, then moved towards a more realistic director based FL approach. There are a number of tutorials done across different models and datasets available in the openfl-tutorials folder that come with the package when you install it. 

Aggregation based approach has some manual copying process of workspaces, certificates etc.  to the connected devices.
Detailed instructions are given in : https://openfl.readthedocs.io/en/latest/running_the_federation.html#step-1-create-a-workspace

If you want to use your own data , you only need to change the data loading part . for example in https://github.com/securefederatedai/openfl/blob/develop/openfl-tutorials/Federated_Keras_MNIST_Tutorial.ipynb , they load keras mnist data using (X_train, y_train), (X_test, y_test) = mnist.load_data(). Instead you can buld your own dataset and convert it by keras datagenerator library and use it for FL. 

You can refer this repo for more details https://github.com/securefederatedai/openfl/tree/develop/openfl-tutorials (examples in interactive api folder uses director based approach).  I would recomend taking one tutorial/template that mostly suits your problem and make adjustments if you are in learning stage. 

I lookforward to implement, as iam now busy with some other projects.
Iam on Linkedin: https://www.linkedin.com/in/muhammad-ashiq-ameer-b496801b2/
